/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int a=22,b=5,c,d,e,f,g;
	c=a+b;
	printf("addition is=%d\n",c);
	d=a-b;
	printf("substraction is=%d\n",d);
    e=a*b;
    printf("multplication is=%d\n",e);
    f=a/b;
    printf("division is=%d\n",f);
    g=a%b;
    printf("modulation is=%d\n",g);
}

